# Generated by Django 6.0.2 on 2026-03-10 16:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus_name", models.CharField(max_length=100)),
                ("operator", models.CharField(blank=True, max_length=100, null=True)),
                ("number", models.CharField(max_length=20, unique=True)),
                (
                    "bus_type",
                    models.CharField(
                        choices=[
                            ("ac_sleeper", "AC Sleeper"),
                            ("ac_seater", "AC Seater"),
                            ("non_ac_sleeper", "Non-AC Sleeper"),
                            ("non_ac_seater", "Non-AC Seater"),
                            ("volvo", "Volvo Multi-Axle"),
                            ("sleeper", "Sleeper Coach"),
                            ("semi_sleeper", "Semi-Sleeper"),
                            ("luxury", "Luxury Coach"),
                        ],
                        max_length=20,
                    ),
                ),
                ("origin", models.CharField(max_length=100)),
                (
                    "origin_coords",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("destination", models.CharField(max_length=100)),
                (
                    "destination_coords",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("departure_time", models.DateTimeField()),
                ("arrival_time", models.DateTimeField()),
                ("total_seats", models.PositiveIntegerField()),
                ("available_seats", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("rating", models.FloatField(default=0.0)),
                ("review_count", models.IntegerField(default=0)),
                ("amenities", models.JSONField(default=list)),
                ("seat_layout", models.JSONField(default=dict)),
                ("route", models.JSONField(default=dict)),
                ("cancellation_policy", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Buses",
                "ordering": ["departure_time"],
            },
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_number", models.CharField(max_length=10)),
                (
                    "seat_type",
                    models.CharField(
                        choices=[
                            ("window", "Window"),
                            ("aisle", "Aisle"),
                            ("sleeper", "Sleeper"),
                            ("sleeper_lower", "Sleeper Lower"),
                            ("sleeper_upper", "Sleeper Upper"),
                            ("disabled", "Disabled"),
                            ("premium", "Premium"),
                            ("emergency", "Emergency Exit"),
                        ],
                        default="window",
                        max_length=15,
                    ),
                ),
                ("is_booked", models.BooleanField(default=False)),
                ("is_locked", models.BooleanField(default=False)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("row", models.PositiveIntegerField()),
                ("column", models.PositiveIntegerField()),
                ("price_multiplier", models.FloatField(default=1.0)),
                ("is_women_only", models.BooleanField(default=False)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="bookings.bus",
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_seats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["row", "column"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_reference",
                    models.CharField(
                        db_index=True, default="TEMP", max_length=10, unique=True
                    ),
                ),
                (
                    "booking_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("journey_date", models.DateField(default=django.utils.timezone.now)),
                ("cancellation_date", models.DateTimeField(blank=True, null=True)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("net_banking", "Net Banking"),
                            ("upi", "UPI"),
                            ("wallet", "Wallet"),
                            ("cod", "Cash on Board"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("payment_status", models.CharField(default="pending", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("refunded", "Refunded"),
                            ("failed", "Payment Failed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_round_trip", models.BooleanField(default=False)),
                ("special_requests", models.TextField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "return_booking",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outbound_booking",
                        to="bookings.booking",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="bookings.bus",
                    ),
                ),
                (
                    "seats",
                    models.ManyToManyField(related_name="bookings", to="bookings.seat"),
                ),
            ],
            options={
                "ordering": ["-booking_date"],
            },
        ),
        migrations.AddIndex(
            model_name="seat",
            index=models.Index(
                fields=["bus", "is_booked"], name="bookings_se_bus_id_8c7adf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="seat",
            index=models.Index(
                fields=["bus", "is_locked"], name="bookings_se_bus_id_27759d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="seat",
            unique_together={("bus", "seat_number")},
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["user", "status"], name="bookings_bo_user_id_69a5d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["booking_reference"], name="bookings_bo_booking_8a7545_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["payment_id"], name="bookings_bo_payment_d73777_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["journey_date", "status"], name="bookings_bo_journey_a0fbdb_idx"
            ),
        ),
    ]
