# Generated by Django 6.0.2 on 2026-07-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus",
            name="amenities",
            field=models.JSONField(
                default=list,
                help_text='Example: ["ac", "wifi", "charging", "water", "blanket"]',
            ),
        ),
        migrations.AlterField(
            model_name="bus",
            name="route",
            field=models.JSONField(
                default=dict,
                help_text='Example: {"distance": "350 km", "duration": "6h 30m", "waypoints": [{"name": "Bengaluru", "lat": 12.9716, "lng": 77.5946}, {"name": "Chennai", "lat": 13.0827, "lng": 80.2707}]}',
            ),
        ),
        migrations.AlterField(
            model_name="bus",
            name="seat_layout",
            field=models.JSONField(
                default=dict,
                help_text='Example: {"rows": 4, "cols": 4, "layout": [["1A", "1B", "", "1C"], ["2A", "2B", "", "2C"], ["3A", "3B", "", "3C"], ["4A", "4B", "", "4C"]]}',
            ),
        ),
    ]
