# Generated by Django 6.0.2 on 2026-07-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_bus_amenities_alter_bus_route_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="driver_name",
            field=models.CharField(
                blank=True, default="Rajesh Kumar", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="bus",
            name="driver_phone",
            field=models.CharField(
                blank=True, default="+91 98765 43210", max_length=20, null=True
            ),
        ),
    ]
