# Generated by Django 6.0.2 on 2026-08-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_bus_driver_name_bus_driver_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="seat",
            name="booked_by_gender",
            field=models.CharField(
                blank=True,
                choices=[("female", "Female"), ("male", "Male")],
                default=None,
                max_length=10,
                null=True,
            ),
        ),
    ]
